# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1ba6381adcc77fa371e4c069b16c41e0a55fb57c24ed63d35f3b78eaf5022c2f929aec7f7765d68047f794140a609bdbdb545ec4ca2dead9189967a9efadb488

test:
  secret_key_base: 074fefbe6f59b44035b6e4310b8e7a7e83ce35ac31fe4b72326240d8cdb695da478b90adfcfc8884ef9e636795e09fd19fd3cf034299376a691b5e25627efe35

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
